export const ENGLISH_INSULTS = Object.freeze({
  general: [
    "Outstanding, {name}. You should be ashamed of yourself.",
    "{name}, the board is stationary. I thought that might help.",
    "Congratulations, {name}: you made three darts look like a public safety incident.",
    "{name}, consider aiming before throwing. It is a revolutionary technique.",
    "Physics has lost faith in you again, {name}.",
    "{name}, even the silence after that turn was uncomfortable.",
    "Three darts, {name}. Not one of them wanted to be involved.",
    "{name}, your accuracy has the structural integrity of wet cardboard.",
    "Some people bring talent, {name}. You bring contrast.",
    "{name}, the dartboard is applying for a restraining order.",
    "Magnificent, {name}. You missed with genuinely moving confidence.",
    "{name}, this is no longer bad luck. It is a repeatable process.",
    "The good news, {name}, is that your turn is over.",
    "{name}, if the goal was to frighten the furniture, flawless work.",
    "I have seen ceiling fans with better aim, {name}.",
    "{name}, every throw is a love letter to mediocrity.",
    "The board has twenty numbers, {name}. You may meet one eventually.",
    "{name}, your technique combines doubt, chaos and a worrying lack of shame.",
    "That was not your worst turn, {name}. Give me time to check the records.",
    "{name}, your opponent does not need a strategy. Waiting will do.",
    "Expectations were low, {name}, and you still found room underneath them.",
    "{name}, talent is chasing you, but you remain comfortably ahead.",
    "Close your eyes next time, {name}. Statistically, it cannot hurt.",
    "{name}, thank you for proving zero can also be a personality.",
    "{name}, your hand-eye coordination appears to be a long-distance relationship.",
    "Nice arm movement, {name}. Shame the dart took part.",
    "{name}, chance is working overtime to disguise your technique.",
    "At this pace, {name}, the next generation will finish the match.",
    "{name}, even your shadow looked away.",
    "The board appreciates you respecting its personal space, {name}.",
    "{name}, you aim like a toaster falling down the stairs.",
    "Another masterpiece of confusion, {name}.",
    "{name}, you just made your previous turn look competent.",
    "Consistency matters, {name}, and you are consistently alarming.",
    "The board does not move, {name}. Neither does your progress.",
    "That turn had three acts, {name}, and all of them were tragedies.",
    "{name}, your game plan seems to be written while the dart is airborne.",
    "An unforgettable turn, {name}. Unfortunately for everyone."
  ],
  low: [
    "{name}, {points} points. A total so small it needs laboratory equipment.",
    "Only {points}, {name}. The board barely noticed.",
    "{points} points, {name}. The darts did more damage to the case.",
    "{name}, celebrating {points} points would be disrespectful to arithmetic.",
    "{points}, {name}. That is not a score; it is a rounding error.",
    "{name}, you scored {points}. The bar was on the floor and you brought a shovel.",
    "{points} points, {name}. I have seen more generous tips.",
    "{name}, {points} points from three darts. A truly miserable distribution.",
    "{points} points, {name}. Even the scoreboard is whispering out of embarrassment.",
    "{name}, you managed {points}. No need to wave to the crowd.",
    "Only {points}, {name}. The effort is assumed because it was not visible.",
    "{name}, {points} points. Technically valid, morally irrelevant.",
    "{points} points, {name}. A yawn would have made more impact.",
    "You scored {points}, {name}. Three darts to produce a footnote.",
    "{name}, {points} points. Failure can count too."
  ],
  bust: [
    "Bust, {name}. Subtraction was part of the game too.",
    "Turn void, {name}. Plenty of power and no detectable thought.",
    "Bust, {name}. You earned nothing with tremendous enthusiasm.",
    "{name}, finishing without a double is like arriving without knowing where you live.",
    "The whole turn in the bin, {name}. At least you lose efficiently.",
    "{name}, you have converted points into regret. Bust.",
    "Bust, {name}. You crossed the line and kept running into ridicule.",
    "{name}, too many points and not enough thinking.",
    "Turn lost, {name}. Basic subtraction defeats you again.",
    "Bust. A superb way to turn an opportunity into decoration, {name}.",
    "{name}, stopping in time was the hard part. Naturally, you did not.",
    "Zero valid points, {name}. The scoreboard has deleted your enthusiasm.",
    "Bust, {name}. Your internal calculator has resigned.",
    "{name}, all that arm movement just to return exactly where you started.",
    "Bust. Next time, try losing in fewer steps, {name}."
  ],
  good: [
    "Not bad, {name}. How uncomfortable to admit it.",
    "{points} points, {name}. Enjoy them before returning to your usual level.",
    "Well thrown, {name}. Even a broken clock is right twice a day.",
    "{name}, that looked almost like talent. Let us not rush to conclusions.",
    "{points} points. You nearly look like someone who can play, {name}.",
    "{name}, {points} points. It went well despite your involvement.",
    "Good turn, {name}. Do not get used to this anomaly.",
    "{points} points, {name}. Talent passed nearby and some of it stuck.",
    "{name}, that was competent. I should check whether the board is rigged.",
    "A disturbing {points} points, {name}. You nearly earned respect.",
    "{name}, you threw well. What an unpleasant turn of events.",
    "{points} points. Save the memory, {name}; it may not happen again.",
    "For a moment you looked dangerous, {name}. It will pass.",
    "Great turn, {name}. Convenient that nobody recorded the others.",
    "{points} points, {name}. Tonight's statistical accident."
  ]
});
